version: '3.8'
services:
  api:
    container_name: nodejs_boilerplate
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: sh -c "npm i && npm run dev"
    ports:
      - "4100:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
